INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) values (1,'Damian','Galvan','damian@gmil.com','2020-08-28','347b33a6-54a5-4aad-9678-48f4331e3341_ale-romo-photography-CLiwQXx7kT8-unsplash.jpg')
INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) values (2,'Jose','Torrez','jose@gmil.com','2020-08-28','')
INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) values (3,'irving','Galvan','damian@gmil.com','2020-08-28','')
INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) values (4,'Carlos','Torrez','jose@gmil.com','2020-08-28','')
INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) values (5,'Jazmin','Galvan','damian@gmil.com','2020-08-28','')
INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) values (6,'Robin','Torrez','jose@gmil.com','2020-08-28','')
INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) values (7,'Mateo','Galvan','damian@gmil.com','2020-08-28','')
INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) values (8,'Talina','Torrez','jose@gmil.com','2020-08-28','')

INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) values (9,'Damian','Galvan','damian@gmil.com','2020-08-28','')
INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) values (10,'Jose','Torrez','jose@gmil.com','2020-08-28','')
INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) values (11,'irving','Galvan','damian@gmil.com','2020-08-28','')
INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) values (12,'Carlos','Torrez','jose@gmil.com','2020-08-28','')
INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) values (13,'Jazmin','Galvan','damian@gmil.com','2020-08-28','')
INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) values (14,'Robin','Torrez','jose@gmil.com','2020-08-28','')
INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) values (15,'Mateo','Galvan','damian@gmil.com','2020-08-28','')
INSERT INTO clientes (id,nombre,apellido,email,create_at,foto) values (16,'Talina','Torrez','jose@gmil.com','2020-08-28','')